#Ces routes seront préfixées de /user



#permet de gerer toute la génération et la réception d'un formulaire utilisateur
sign_in:
    path:     /add
    defaults: { _controller: UserBundle:User:add }

#page principale d'un utilisateur.
user_mainpage:
    path: /{id}
    defaults: { _controller: UserBundle:User:mainpage}
    requirements:
            id: \d+

#page permettant de lister l'ensemble de ses projets et de voir les invitations recues
user_projects:
    path:     /projects
    defaults: { _controller: UserBundle:User:invitationsProjects}